Exercise feature
MindPrepDev/Hello-Microverse pull request #1
Opened 2022-04-19 22:43 UTC by MindPrepDev

This is my completed exercise on opening a pull request.

2022-04-19 23:02 UTC, JuliCarracedo requested changes
Hi @MindPrepDev , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

- [x] You must use the provided [README template](https://github.com/microverseinc/readme-template/blob/master/README.md) for your README to be considered professional
- [ ] Your linters are failing. Make sure you follow [this documentation](https://github.com/microverseinc/linters-config/tree/master/html-css) to solve all linter errors locally before pushing changes to your PR.
- [ ] Both the branch name and the PR title must reflect what is being brought into the project. Try something more descriptive of your awesome work!

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-20 10:12 UTC, danmainah requested changes
Hi @MindPrepDev , 

Great work on making the changes requested by a previous reviewer 👏  👏 👏
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights

✔️ Github flow was correctly used
✔️  Good design
✔️  Good PR and Description

 # Required Changes ♻️

- [ ] Kindly make sure all your linter checks are passing, currently, I can see your Stylelint is not passing, it seems it can't locate any CSS file as indicated in the report below, try my suggestion of moving your style.css file from the current folder to the same folder as index.html.
![image](https://user-images.githubusercontent.com/61408860/164205430-06ff15e3-0218-4a36-81bc-74024e999508.png)


_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-20 10:12 UTC, danmainah commented on .gitignore
> +This file should be ignored by git
- [ ] [OPTIONAL] Kindly ensure to add `test.md` file to `.gitignore` file, currently its not there.

2022-04-20 10:12 UTC, danmainah commented on .github/style.css
> +}
- [ ] [OPTIONAL] Kindly ensure your `style.css` file is in the correct location, its a bad practise to have it in your linters folder.

2022-04-20 13:13 UTC, MindPrepDev commented on .github/style.css
> +}
[Please check the link to the renamed branch that has the correction you suggested](https://github.com/MindPrepDev/Hello-Microverse/pull/2)

@JuliCarracedo suggested I rename the branch feature to a more descriptive one and that is what I have done. Can I go ahead to delete Exercise-feature branch now, since it has been replaced by Feature-branch? Also, I added the test.md file to git ignore with my style.css in a separate folder. 

After checking my repo, I found it passed all test cases. Could you please check it out again and let me know how you feel about it? 
*Thank you very much!*

2022-04-21 18:24 UTC, keroloussamy approved these changes
Hi @MindPrepDev, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## To highlight 🎯

- No linter errors.✔️
- Good code design and implementation. ✔️
- Add all the requirements. ✔️

![clap](https://media0.giphy.com/media/j2GPljpvL8Lulm3d0X/giphy.gif)



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-21 19:57 UTC, MindPrepDev commented
Yes! Thanks @keroloussamy

2022-04-21 19:58 UTC, merged